name: Checkmarx SAST Scan

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v2.3
        with:
          checkmarx_url: '${{ secrets.CX_SERVER_URL }}'
          checkmarx.version: '9.1'
          checkmarx_username: '${{ secrets.CX_USERNAME }}'
          checkmarx_password: '${{ secrets.CX_PASSWORD }}'
      - name: Upload SARIF
        if: success()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx_result.sarif
