name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ${{ github.repository }}
          cx_tenant: bmx
          base_uri: https://ast.checkmarx.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          branch: ${{ github.ref }}
          additional_params: --report-format json --output-path . --scan-types sast
      - name: mobbdev
        # You may pin to the exact commit or the version.
        # uses: mobb-dev/action@7e7a72ff0b13c545d810ff05e08119274626b74b
        uses: mobb-dev/action@v1
        with:
          # Path to SAST report file
          report-file: "cx_result.json"
          # Mobb API key
          api-key: ${{ secrets.MOBB_KEY }}
          # GitaHub Token
          github-token: ${{ secrets.GITHUB_TOKEN }}
