name: Checkmarx SAST Scan

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: 
      - master
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          project: ${{ github.repository }}-PR
          team: /CxServer
          checkmarx_url: 'https://emelnik.onthewifi.com/'
          checkmarx_username: 'admin'
          checkmarx_password: 'Cx!234567'
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          scanners: sast
          bug_tracker: Sarif
          extra_certificates: certificate
      - name: Upload SARIF
        if: success()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx_result.sarif
