name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        run: |
          wget https://github.com/Checkmarx/ast-cli/releases/download/2.0.54/ast-cli_2.0.54_linux_x64.tar.gz -O checkmarx.tar.gz
          tar -xf checkmarx.tar.gz
          ./cx configure set --prop-name cx_apikey --prop-value ${{ secrets.CX_API_KEY }}
          ./cx configure set --prop-name cx_base_auth_uri --prop-value ${{ secrets.CX_BASE_AUTH_URI }}
          ./cx configure set --prop-name cx_base_uri --prop-value ${{ secrets.CX_BASE_URI }}
          ./cx configure set --prop-name cx_tenant --prop-value ${{ secrets.CX_TENANT }}
          shell: bash -l {0}

      - name: Run Checkmarx SAST scan
        run: |
          ./cx scan create --project-name my-test-project -s ./ --report-format json --scan-types sast --branch nobranch  --threshold "sast-high=1" 
          shell: bash -l {0}
        
      - name: mobbdev
        # You may pin to the exact commit or the version.
        # uses: mobb-dev/action@7e7a72ff0b13c545d810ff05e08119274626b74b
        uses: mobb-dev/action@v1
        with:
          # Path to SAST report file
          report-file: "cx_result.json"
          # Mobb API key
          api-key: ${{ secrets.MOBB_KEY }}
          # GitaHub Token
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
